# -*- coding: utf-8 -*-
"""Aula 1 de Processamento de Imagens - 22/03/2021.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cbtq07qSlOugAvu1UYdPNQJFGhrA_1Wg
"""

import numpy as np
import pandas as pd
import matplotlib as plt
import math

#exec1
m = np.full((5, 10), 7)

#exec2
m2 = np.random.randn(200, 400)
m2[m2 > 0] = 0

#exec3
a = np.random.randn(30)
print(a)
b = a[::-1]
print(b)

#exec5
m5 = np.random.randn(30)
print("m5", m5)
max = m5.max()
print("max", max)
m6 = m5[m5 != max]
print("m6", m6)

#exec6
m7 = np.random.randn(6)
print(m7)
mask = m7 > 0
m8 = np.log(m7[mask])
print(m8)

#exec7
m9 = np.random.randn(6, 4)
print(m9.trace())

#exec9
m9 = np.random.randn(6, 4)
print(m9)
max = 1.2
min = 1.0
m9[m9 < min] = min
m9[m9 > max] = max
print(m9)

#exec10
x = np.linspace(-2., 2., 5)
print(x)
y = np.where(x <= 0.5, x**2, -x)
print(y)

#exec12
x = np.linspace(-2., 2., 5)
print("x", x)
y = np.linspace(-2., 2., 5)
print("y", y)
z = np.add(x, y)
print("z", z)

#exec13
x = np.array([1, 2, 3, 4])
print("x", x)
y = np.array([10, 20, 30, 40])
print("y", y)
z = y.sum() * x.sum()
print("sum", z)

#####
#1
x = np.array([False, True, False, False, True, False, True])
print(np.count_nonzero([x[:-1] > x[1:]]))

#2 
x = np.array([1,2,3,4])
print(x[x % 2 == 1]**2)

#3 
x = np.array([1,5,12,15,20,22])
print(x[x % 5 == 0].sum())

#4 
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
n = 4
print(np.add.reduceat(x, np.arange(0, len(x), n)))

#5
x = np.array([-3, -2, -1, 0, 1, 2, 3])
x[x < 0] = 0
print(x)

#6
x = np.array([1, 2, 3, 4, 5, 6, 7])
print(len(x[x%2 == 0]))

#7
x = np.array([1, 2, 3, 4, 5, 4, 3, 2, 1, 2, 3, 2, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1])
print(x[1:-1][np.diff(np.diff(x)) < 0])

#8
def is_prime(v):
  x = np.arange(1, v+1)
  x = np.where(v % x == 0, 1, 0)
  print(x.sum())
  if x.sum() == 2:
    print("Primo")
  else:
    print("Não Primo")

is_prime(20)
is_prime(2)